### ISSUE TITLE
Case insensitive main module matching

### ISSUE THREAD

**Issue by v-p-b** [0ffffffffh/dragondance#14]
I'm trying to parse a DRCOV output generated by an independent tool. It seems, that Dragon Dance tries to apply coverage information from modules other than the one loaded in Ghidra, resulting in `InvalidInstructionAddress` exceptions. 

I looked around in the code a bit and couldn't find anything responsible for filtering the coverage data to the currently loaded module only, but I may be missing something since it's a Saturday morning...

Can you provide some advice whether:
- This kind of input should be supported by Dragon Dance?
- If it is supported, where can I find the code responsible for filtering?
- If currently not supported would it make sense to add support, or should users adjust their external tools instead?

**Comment by 0ffffffffh** [comment]
Hi

Could you help me to clarify some points?

What's the independent tool that generates the drcov output? As far I know the drcov is the only coverage collector module that it drives by drrun of dynamorio. Did you mean that you are using some kind of modified version of the drcov?

So the drcov output has it's own standard format. Dragondance must read correctly. Here is the portion of the drcov parser. 

https://github.com/0ffffffffh/dragondance/blob/68863c79aec9f5de786664625c577eff083cb7a4/src/main/java/dragondance/datasource/DynamorioDataSource.java#L53-L75

So I'm wondering is there a output format difference between yours and the standard drcov's. You can share the output if you want that might be helpful.

Dragondance loads coverage data for main module only. It filters out any other modules coverage data. Here is the portion of that code.

https://github.com/0ffffffffh/dragondance/blob/3f003d259d3e8295627f6744c9233f831a57550d/src/main/java/dragondance/datasource/CoverageDataSource.java#L337-L340

**Comment by v-p-b** [comment]
I'm using a custom tool I made based on the one provided in [Lighthouse](https://github.com/gaasedelen/lighthouse) for Frida, but I encountered a couple of similar tools here and there (I also created some ugly hacks like [this](https://gist.github.com/v-p-b/238d2e3bfa6671904f7e416e8a8ca562)) - as I see the output format of DRCOV became a standard of sorts that many tools try to follow with more or less success...

It seems I missed the last code part you included, I will investigate from there and update the issue if necessary. Thank you!

**Comment by v-p-b** [comment]
OK, so the problem seems to be that `CoverageDatasource.pushModule()` does case sensitive comparison to identify the main module, while in case of modules for Windows, case mismatch is pretty common. This results in `pushEntry()` adding all collected blocks (`this.mainModule == null`), although their offsets obviously don't make sense. 

Do you think it's appropriate to always to a case insensitive check, or should this be dependent of other factors (like a check if the loaded module is a PE, and if so, go insensitive)?

**Comment by janbbeck** [comment]
I just had that discussion with the developer of bncov for binary ninja a couple of days ago. He decided to change the change the bncov parser to be case insensitive.

Lighthouse is case insensitive and does fuzzy matching. Additionally, he changed the behavior a few days ago to pop up a selection menu if it cant find a matching entry.
![slack-imgs com](https://user-images.githubusercontent.com/11450961/79677478-9fbd1e80-81fa-11ea-926e-fb62a18fa03b.png)

**Comment by 0ffffffffh** [comment]
> 
> 
> OK, so the problem seems to be that `CoverageDatasource.pushModule()` does case sensitive comparison to identify the main module, while in case of modules for Windows, case mismatch is pretty common. This results in `pushEntry()` adding all collected blocks (`this.mainModule == null`), although their offsets obviously don't make sense.
> 
> Do you think it's appropriate to always to a case insensitive check, or should this be dependent of other factors (like a check if the loaded module is a PE, and if so, go insensitive)?

That's right. I think the case-insensitive check would be enough for this. So, can you confirm that there is casing difference between module name provided by ghidra and the path which is in your coverage output file? Do you believe the fix would solve your problem?

**Comment by v-p-b** [comment]
Yes, I tested the case insensitive check, and it works. In debugger I could also see the case mismatch. I can open a PR later today.
