### ISSUE TITLE
Unable to install extension

### ISSUE THREAD

**Issue by FuzzySecurity** [0ffffffffh/dragondance#18]
I am on ghidra_9.1.2_PUBLIC_20200212 and I am unable to install the extension:
![image](https://user-images.githubusercontent.com/10997340/83072560-e35f3f80-a066-11ea-85bb-763dce61034c.png)

**Comment by janbbeck** [comment]
you need to build dragondance for ghidra 9.1.2,
detailed instructions are available at
https://github.com/0ffffffffh/dragondance

under 'Build Instructions'

**Comment by FuzzySecurity** [comment]
My bad I assumed the release zip was the compiled plugin.

**Comment by FuzzySecurity** [comment]
I see, what you mean is, the release package is out-of-date. It would be good to keep an updated package in releases.
