### ISSUE TITLE
README.md: Launching Dragon Dance

### ISSUE THREAD

**Issue by jjoonathan** [0ffffffffh/dragondance#4]
Thank you for putting together this plugin, and for putting together a detailed and well-illustrated README.md. The screenshots quickly helped me decide that your tool was the right tool, the "Installation" section successfully walked me through the install, and the "Collecting Coverage Data" successfully walked me through collecting traces with dynamorio. I had only done this in PIN before, so your instructions introduced me to dynamorio and were quite painless. Thanks!

Unfortunately, that's where I get lost. I want to load the traces into dragondance, but I can't figure out how to get a dragondance panel next to my disassembly. Dragon Dance is installed in Ghidra -- it is listed with a checked checkbox in the "Install Extensions" window -- but I can't figure out how to open it. I open the dll I want to investigate and look in the "Tools" menu, the "Windows" menu, and in right-click menus on my disassembly / graph view, but I don't see dragon dance listed anywhere, and I have tried every likely icon I've seen.

I am able to "Main Project Window > Create Tool > Dragon Dance" and this creates a dragon dance window that looks very much like the screenshots, but if I click "+" and try to load the dynamorio traces it gets an error on account of not being attached to any particular exe/dll. I suspect this is not how dragon dance should be invoked, and I suspect invoking it at the project level rather than the dll/exe level created the problem, but I don't know enough about ghidra plugins to guess the correct way to open Dragon Dance.

Anyway, the substance of this issue is to add a section to README.md after "Installation" and "Collecting Coverage Data," perhaps called "Launching Dragon Dance," that documents how to open the Dragon Dance panel on a loaded dll/exe. Even if it is very obvious, I can't seem to figure it out, so it is evidently not foolproof :)

Thanks,
deWerd

PS
I am using Ghidra 9.0.2 and v0.2.1 release.

**Comment by 0ffffffffh** [comment]
Hi @jjoonathan 

Thank you for your suggestion. I agree with you. So I have updated the Readme.md with the Launching Instructions. Could you follow these instructions? I believe that would be work.

Thanks.

**Comment by jjoonathan** [comment]
Thanks, the new instructions worked great!
