### ISSUE TITLE
Main Module Detection

### ISSUE THREAD

**Issue by jjoonathan** [0ffffffffh/dragondance#5]
Hi!

Me again, this time with a bug (or user error :) ) when loading my trace file (dynamorio drcov dump_binary). I get "Invalid instruction address (180053840) possible reasons: 1) the binary could be a different version of the program the MD5 hash of the currently loaded image is "12345..." 2) you forgot to reload the updated binary into ghidra 3) you tried to load a coverage data to the mismatched program".

The first thing I did was to check the MD5 in the message box against the MD5 of the file I opened in ghidra and the file I ran to obtain the dump. All three MD5s match.

Then I looked at address 0x180053840. It was in the middle of an instruction.

Then I looked into the dynamorio dump itself. The very first basic block is (offset=0x53840 hits=13 moduleId=4). According to the dump header, moduleId 4 is ntdll.dll, but I am not analyzing ntdll.dll, I am analyzing MySpecialDllName.dll. The desired behavior would be to ignore this basic block on account of it being in a different module.

I then looked at the Dragon Dance source. It looks like CoverageDataSource has a notion of "main module" -- it scans every module in the dump to see if the path ends with currentProgram.getDomainFile().getName() and if it finds such a module, it calls it the "main module" and filters out all basic blocks not belonging to the main module. That's exactly what I want, I just need to figure out why it isn't working.  I verified the string matching manually -- currentProgram.getDomainFile().getName() is a suffix for exactly one module in the dynamorio dump, module number 165, yet evidently it does not detect this as the main module or else it would have filtered out the first basic block  due to moduleId=4 not matching mainModuleId=165.

To proceed further on my own, I will need to set up a development environment, or at least turn on logging. I anticipate that might take some time, so I thought I would see if you had any likely theories first :)

I would be happy to share the dll and the trace privately if it would help.

Thanks again,
deWerd

**Comment by 0ffffffffh** [comment]
Hi

That's quite interesting issue, I would like to inspect it myself. Could you share the Dll and the trace file with me? My initial thought was endsWith failure due to possible case sensitive mismatch. But you as you mentioned, you had verified the string matching. 

Thanks

**Comment by jjoonathan** [comment]
Here are the dll and trace: https://www.dropbox.com/s/n4wccynoeewntw5/test_files.zip?dl=0

I have confirmed that the same issue appears in a fresh Ghidra project containing only the dll.

As you might have guessed from the obfuscated specifics in my original post, I would appreciate if we could avoid pushing specifics -- even the dll name -- into easy reach of search engines.

Thanks for taking a look!

**Comment by 0ffffffffh** [comment]
Hi, I respect your desire of course.

I have got required files. So you can even remove the link or remove the files from your cloud service. 
I will inspect the issue I will back to you when I finished.

Thank you.

**Comment by 0ffffffffh** [comment]
Hi again @jjoonathan 

I have identified the problem and I have fixed the issue that I tagged as #6 

I pushed the fixed version which is version 0.2.2. I have tested the fixed version of dragondance using the binary and the coverage data supplied by you. It worked well with it. So could you try that too?

Thanks for your feedback.

**Comment by jjoonathan** [comment]
Thanks, the updated version works great!
