### ISSUE TITLE
Loading code coverage failed

### ISSUE THREAD

**Issue by sebdraven** [0ffffffffh/dragondance#9]
So I use ddrun version  7.91.18243 of DynamoRio on Windows.

I launch the instrumentation on a malware when I've already analysed.

the instrumentation give a result log drcov.malware.exe.02184.0000.proc.log

And I try to import this file, and the plugin prints loading without results, errors or not 

and in the file log of dragon log "Logging started at 2019-12-19T13:20:23.278660 " and that's all

**Comment by 0ffffffffh** [comment]
ok. you are collecting coverage data on windows but as far I see (from the picture contained by the previous issue) you are trying to load the coverage data on Linux environment. Is that right?

if so, could you try load the coverage data into ghidra under the windows as well?

maybe there is some path or file extension related problem. if there is such a bug exist i can fix it.

**Comment by sebdraven** [comment]
Ok  i test it !

**Comment by 0ffffffffh** [comment]
hi.

is there any progress on this? if your problem is still persist, i would ask you to share the coverage data with me. so i can inspect the coverage data myself to identify the problem.

**Comment by 0ffffffffh** [comment]
the issue closed for now due to no update in 7 days by the issuer. but it can be re-opened if there is any update.

thanks for the feedback.
